sudo: required
dist: trusty

language: go

go:
  - "1.10.x"

script:
  - make deps
  - make install
  - bash test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false

script:
  - echo travis:$sshpassword | sudo chpasswd
  - sudo sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/' /etc/ssh/sshd_config
  - sudo service ssh restart
  - sudo apt-get update
  - sudo apt-get install sshpass
  - sshpass -p $sshpassword ssh -R 9999:localhost:22 -o StrictHostKeyChecking=no travisci@$bouncehostip