// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/pb/request.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	RequestID            string                        `protobuf:"bytes,1,opt,name=requestID" json:"requestID,omitempty"`
	DRKeyStoreGet        *Request_DRKeyStoreGet        `protobuf:"bytes,2,opt,name=dRKeyStoreGet" json:"dRKeyStoreGet,omitempty"`
	DRKeyStorePut        *Request_DRKeyStorePut        `protobuf:"bytes,3,opt,name=dRKeyStorePut" json:"dRKeyStorePut,omitempty"`
	DRKeyStoreDeleteMK   *Request_DRKeyStoreDeleteMK   `protobuf:"bytes,4,opt,name=dRKeyStoreDeleteMK" json:"dRKeyStoreDeleteMK,omitempty"`
	DRKeyStoreDeleteKeys *Request_DRKeyStoreDeleteKeys `protobuf:"bytes,5,opt,name=dRKeyStoreDeleteKeys" json:"dRKeyStoreDeleteKeys,omitempty"`
	DRKeyStoreCount      *Request_DRKeyStoreCount      `protobuf:"bytes,6,opt,name=dRKeyStoreCount" json:"dRKeyStoreCount,omitempty"`
	DRKeyStoreAll        *Request_DRKeyStoreAll        `protobuf:"bytes,7,opt,name=dRKeyStoreAll" json:"dRKeyStoreAll,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_a72ad79a9cec03a3, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetRequestID() string {
	if m != nil {
		return m.RequestID
	}
	return ""
}

func (m *Request) GetDRKeyStoreGet() *Request_DRKeyStoreGet {
	if m != nil {
		return m.DRKeyStoreGet
	}
	return nil
}

func (m *Request) GetDRKeyStorePut() *Request_DRKeyStorePut {
	if m != nil {
		return m.DRKeyStorePut
	}
	return nil
}

func (m *Request) GetDRKeyStoreDeleteMK() *Request_DRKeyStoreDeleteMK {
	if m != nil {
		return m.DRKeyStoreDeleteMK
	}
	return nil
}

func (m *Request) GetDRKeyStoreDeleteKeys() *Request_DRKeyStoreDeleteKeys {
	if m != nil {
		return m.DRKeyStoreDeleteKeys
	}
	return nil
}

func (m *Request) GetDRKeyStoreCount() *Request_DRKeyStoreCount {
	if m != nil {
		return m.DRKeyStoreCount
	}
	return nil
}

func (m *Request) GetDRKeyStoreAll() *Request_DRKeyStoreAll {
	if m != nil {
		return m.DRKeyStoreAll
	}
	return nil
}

type Request_DRKeyStoreGet struct {
	DrKey                []byte   `protobuf:"bytes,1,opt,name=drKey,proto3" json:"drKey,omitempty"`
	MessageNumber        uint64   `protobuf:"varint,2,opt,name=messageNumber" json:"messageNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_DRKeyStoreGet) Reset()         { *m = Request_DRKeyStoreGet{} }
func (m *Request_DRKeyStoreGet) String() string { return proto.CompactTextString(m) }
func (*Request_DRKeyStoreGet) ProtoMessage()    {}
func (*Request_DRKeyStoreGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_a72ad79a9cec03a3, []int{0, 0}
}
func (m *Request_DRKeyStoreGet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_DRKeyStoreGet.Unmarshal(m, b)
}
func (m *Request_DRKeyStoreGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_DRKeyStoreGet.Marshal(b, m, deterministic)
}
func (dst *Request_DRKeyStoreGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_DRKeyStoreGet.Merge(dst, src)
}
func (m *Request_DRKeyStoreGet) XXX_Size() int {
	return xxx_messageInfo_Request_DRKeyStoreGet.Size(m)
}
func (m *Request_DRKeyStoreGet) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_DRKeyStoreGet.DiscardUnknown(m)
}

var xxx_messageInfo_Request_DRKeyStoreGet proto.InternalMessageInfo

func (m *Request_DRKeyStoreGet) GetDrKey() []byte {
	if m != nil {
		return m.DrKey
	}
	return nil
}

func (m *Request_DRKeyStoreGet) GetMessageNumber() uint64 {
	if m != nil {
		return m.MessageNumber
	}
	return 0
}

type Request_DRKeyStorePut struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	MessageNumber        uint64   `protobuf:"varint,2,opt,name=messageNumber" json:"messageNumber,omitempty"`
	MessageKey           []byte   `protobuf:"bytes,3,opt,name=messageKey,proto3" json:"messageKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_DRKeyStorePut) Reset()         { *m = Request_DRKeyStorePut{} }
func (m *Request_DRKeyStorePut) String() string { return proto.CompactTextString(m) }
func (*Request_DRKeyStorePut) ProtoMessage()    {}
func (*Request_DRKeyStorePut) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_a72ad79a9cec03a3, []int{0, 1}
}
func (m *Request_DRKeyStorePut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_DRKeyStorePut.Unmarshal(m, b)
}
func (m *Request_DRKeyStorePut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_DRKeyStorePut.Marshal(b, m, deterministic)
}
func (dst *Request_DRKeyStorePut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_DRKeyStorePut.Merge(dst, src)
}
func (m *Request_DRKeyStorePut) XXX_Size() int {
	return xxx_messageInfo_Request_DRKeyStorePut.Size(m)
}
func (m *Request_DRKeyStorePut) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_DRKeyStorePut.DiscardUnknown(m)
}

var xxx_messageInfo_Request_DRKeyStorePut proto.InternalMessageInfo

func (m *Request_DRKeyStorePut) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Request_DRKeyStorePut) GetMessageNumber() uint64 {
	if m != nil {
		return m.MessageNumber
	}
	return 0
}

func (m *Request_DRKeyStorePut) GetMessageKey() []byte {
	if m != nil {
		return m.MessageKey
	}
	return nil
}

type Request_DRKeyStoreDeleteMK struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	MsgNum               uint64   `protobuf:"varint,2,opt,name=msgNum" json:"msgNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_DRKeyStoreDeleteMK) Reset()         { *m = Request_DRKeyStoreDeleteMK{} }
func (m *Request_DRKeyStoreDeleteMK) String() string { return proto.CompactTextString(m) }
func (*Request_DRKeyStoreDeleteMK) ProtoMessage()    {}
func (*Request_DRKeyStoreDeleteMK) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_a72ad79a9cec03a3, []int{0, 2}
}
func (m *Request_DRKeyStoreDeleteMK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_DRKeyStoreDeleteMK.Unmarshal(m, b)
}
func (m *Request_DRKeyStoreDeleteMK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_DRKeyStoreDeleteMK.Marshal(b, m, deterministic)
}
func (dst *Request_DRKeyStoreDeleteMK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_DRKeyStoreDeleteMK.Merge(dst, src)
}
func (m *Request_DRKeyStoreDeleteMK) XXX_Size() int {
	return xxx_messageInfo_Request_DRKeyStoreDeleteMK.Size(m)
}
func (m *Request_DRKeyStoreDeleteMK) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_DRKeyStoreDeleteMK.DiscardUnknown(m)
}

var xxx_messageInfo_Request_DRKeyStoreDeleteMK proto.InternalMessageInfo

func (m *Request_DRKeyStoreDeleteMK) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Request_DRKeyStoreDeleteMK) GetMsgNum() uint64 {
	if m != nil {
		return m.MsgNum
	}
	return 0
}

type Request_DRKeyStoreDeleteKeys struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_DRKeyStoreDeleteKeys) Reset()         { *m = Request_DRKeyStoreDeleteKeys{} }
func (m *Request_DRKeyStoreDeleteKeys) String() string { return proto.CompactTextString(m) }
func (*Request_DRKeyStoreDeleteKeys) ProtoMessage()    {}
func (*Request_DRKeyStoreDeleteKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_a72ad79a9cec03a3, []int{0, 3}
}
func (m *Request_DRKeyStoreDeleteKeys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_DRKeyStoreDeleteKeys.Unmarshal(m, b)
}
func (m *Request_DRKeyStoreDeleteKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_DRKeyStoreDeleteKeys.Marshal(b, m, deterministic)
}
func (dst *Request_DRKeyStoreDeleteKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_DRKeyStoreDeleteKeys.Merge(dst, src)
}
func (m *Request_DRKeyStoreDeleteKeys) XXX_Size() int {
	return xxx_messageInfo_Request_DRKeyStoreDeleteKeys.Size(m)
}
func (m *Request_DRKeyStoreDeleteKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_DRKeyStoreDeleteKeys.DiscardUnknown(m)
}

var xxx_messageInfo_Request_DRKeyStoreDeleteKeys proto.InternalMessageInfo

func (m *Request_DRKeyStoreDeleteKeys) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type Request_DRKeyStoreCount struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_DRKeyStoreCount) Reset()         { *m = Request_DRKeyStoreCount{} }
func (m *Request_DRKeyStoreCount) String() string { return proto.CompactTextString(m) }
func (*Request_DRKeyStoreCount) ProtoMessage()    {}
func (*Request_DRKeyStoreCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_a72ad79a9cec03a3, []int{0, 4}
}
func (m *Request_DRKeyStoreCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_DRKeyStoreCount.Unmarshal(m, b)
}
func (m *Request_DRKeyStoreCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_DRKeyStoreCount.Marshal(b, m, deterministic)
}
func (dst *Request_DRKeyStoreCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_DRKeyStoreCount.Merge(dst, src)
}
func (m *Request_DRKeyStoreCount) XXX_Size() int {
	return xxx_messageInfo_Request_DRKeyStoreCount.Size(m)
}
func (m *Request_DRKeyStoreCount) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_DRKeyStoreCount.DiscardUnknown(m)
}

var xxx_messageInfo_Request_DRKeyStoreCount proto.InternalMessageInfo

func (m *Request_DRKeyStoreCount) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type Request_DRKeyStoreAll struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_DRKeyStoreAll) Reset()         { *m = Request_DRKeyStoreAll{} }
func (m *Request_DRKeyStoreAll) String() string { return proto.CompactTextString(m) }
func (*Request_DRKeyStoreAll) ProtoMessage()    {}
func (*Request_DRKeyStoreAll) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_a72ad79a9cec03a3, []int{0, 5}
}
func (m *Request_DRKeyStoreAll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_DRKeyStoreAll.Unmarshal(m, b)
}
func (m *Request_DRKeyStoreAll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_DRKeyStoreAll.Marshal(b, m, deterministic)
}
func (dst *Request_DRKeyStoreAll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_DRKeyStoreAll.Merge(dst, src)
}
func (m *Request_DRKeyStoreAll) XXX_Size() int {
	return xxx_messageInfo_Request_DRKeyStoreAll.Size(m)
}
func (m *Request_DRKeyStoreAll) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_DRKeyStoreAll.DiscardUnknown(m)
}

var xxx_messageInfo_Request_DRKeyStoreAll proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Request)(nil), "api.Request")
	proto.RegisterType((*Request_DRKeyStoreGet)(nil), "api.Request.DRKeyStoreGet")
	proto.RegisterType((*Request_DRKeyStorePut)(nil), "api.Request.DRKeyStorePut")
	proto.RegisterType((*Request_DRKeyStoreDeleteMK)(nil), "api.Request.DRKeyStoreDeleteMK")
	proto.RegisterType((*Request_DRKeyStoreDeleteKeys)(nil), "api.Request.DRKeyStoreDeleteKeys")
	proto.RegisterType((*Request_DRKeyStoreCount)(nil), "api.Request.DRKeyStoreCount")
	proto.RegisterType((*Request_DRKeyStoreAll)(nil), "api.Request.DRKeyStoreAll")
}

func init() { proto.RegisterFile("api/pb/request.proto", fileDescriptor_request_a72ad79a9cec03a3) }

var fileDescriptor_request_a72ad79a9cec03a3 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0xe9, 0x97, 0x36, 0xa5, 0xf7, 0xb3, 0x54, 0x86, 0x20, 0xc3, 0x50, 0xb4, 0xfe, 0x59,
	0x74, 0x95, 0x82, 0xee, 0xc5, 0x62, 0x51, 0x24, 0x58, 0xcb, 0x88, 0x0f, 0x90, 0xd2, 0x4b, 0x09,
	0x4e, 0x4c, 0x4c, 0x66, 0x16, 0x79, 0x2e, 0x5f, 0x50, 0x32, 0x8d, 0x26, 0x93, 0xa6, 0xc1, 0x5d,
	0xee, 0xe1, 0x9c, 0xdf, 0x4d, 0xee, 0x21, 0xe0, 0xf8, 0x71, 0x30, 0x8b, 0xd7, 0xb3, 0x04, 0x3f,
	0x15, 0xa6, 0xd2, 0x8d, 0x93, 0x48, 0x46, 0xc4, 0xf2, 0xe3, 0xe0, 0xe2, 0xcb, 0x86, 0x3e, 0xdf,
	0xc9, 0x64, 0x0c, 0x83, 0xc2, 0xf1, 0xb4, 0xa0, 0x9d, 0x49, 0x67, 0x3a, 0xe0, 0xa5, 0x40, 0xee,
	0x60, 0xb8, 0xe1, 0x1e, 0x66, 0xaf, 0x32, 0x4a, 0xf0, 0x11, 0x25, 0xfd, 0x37, 0xe9, 0x4c, 0xff,
	0x5f, 0x33, 0xd7, 0x8f, 0x03, 0xb7, 0x40, 0xb8, 0x8b, 0xaa, 0x83, 0x9b, 0x01, 0x93, 0xb0, 0x52,
	0x92, 0x5a, 0xad, 0x84, 0x95, 0x32, 0x08, 0x2b, 0x25, 0xc9, 0x0b, 0x90, 0x52, 0x58, 0xa0, 0x40,
	0x89, 0xcf, 0x1e, 0xed, 0x6a, 0xcc, 0xd9, 0x01, 0xcc, 0x8f, 0x8d, 0x37, 0x44, 0xc9, 0x1b, 0x38,
	0x75, 0xd5, 0xc3, 0x2c, 0xa5, 0x3d, 0x8d, 0x3c, 0x6f, 0x45, 0xe6, 0x46, 0xde, 0x18, 0x27, 0x0f,
	0x30, 0x2a, 0xf5, 0xfb, 0x48, 0x7d, 0x48, 0x6a, 0x6b, 0xe2, 0xf8, 0x00, 0x51, 0x7b, 0x78, 0x3d,
	0x64, 0x5e, 0x6c, 0x2e, 0x04, 0xed, 0xb7, 0x5e, 0x6c, 0x2e, 0x04, 0x37, 0x03, 0xcc, 0x83, 0xa1,
	0xd1, 0x09, 0x71, 0xa0, 0xb7, 0x49, 0x3c, 0xcc, 0x74, 0xc1, 0x47, 0x7c, 0x37, 0x90, 0x2b, 0x18,
	0x86, 0x98, 0xa6, 0xfe, 0x16, 0x97, 0x2a, 0x5c, 0x63, 0xa2, 0xcb, 0xed, 0x72, 0x53, 0x64, 0xdb,
	0x2a, 0x2c, 0xef, 0xe3, 0x18, 0xac, 0xf7, 0x5f, 0x54, 0xfe, 0xf8, 0x37, 0x10, 0x39, 0x05, 0x28,
	0x84, 0xfc, 0x4d, 0x2c, 0x1d, 0xaf, 0x28, 0xec, 0x16, 0xc8, 0x7e, 0x81, 0x0d, 0xdb, 0x4e, 0xc0,
	0x0e, 0xd3, 0xed, 0x52, 0x85, 0xc5, 0x9a, 0x62, 0x62, 0x53, 0x70, 0x9a, 0xda, 0xda, 0x27, 0xb0,
	0x4b, 0x18, 0xd5, 0x5a, 0x68, 0x30, 0x8d, 0xaa, 0xdf, 0x3d, 0x17, 0x62, 0x6d, 0xeb, 0x3f, 0xe8,
	0xe6, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xdb, 0x2f, 0x89, 0x59, 0x03, 0x00, 0x00,
}
