// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/pb/response.proto

package api_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Response struct {
	DRKeyStoreGet           *Response_DRKeyStoreGet           `protobuf:"bytes,3,opt,name=dRKeyStoreGet" json:"dRKeyStoreGet,omitempty"`
	DRKeyStoreCount         *Response_DRKeyStoreCount         `protobuf:"bytes,4,opt,name=dRKeyStoreCount" json:"dRKeyStoreCount,omitempty"`
	DRKeyStoreAll           *Response_DRKeyStoreAll           `protobuf:"bytes,5,opt,name=dRKeyStoreAll" json:"dRKeyStoreAll,omitempty"`
	SendEthereumTransaction *Response_SendEthereumTransaction `protobuf:"bytes,6,opt,name=sendEthereumTransaction" json:"sendEthereumTransaction,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                          `json:"-"`
	XXX_unrecognized        []byte                            `json:"-"`
	XXX_sizecache           int32                             `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_e1cf38aee75d74c7, []int{0}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetDRKeyStoreGet() *Response_DRKeyStoreGet {
	if m != nil {
		return m.DRKeyStoreGet
	}
	return nil
}

func (m *Response) GetDRKeyStoreCount() *Response_DRKeyStoreCount {
	if m != nil {
		return m.DRKeyStoreCount
	}
	return nil
}

func (m *Response) GetDRKeyStoreAll() *Response_DRKeyStoreAll {
	if m != nil {
		return m.DRKeyStoreAll
	}
	return nil
}

func (m *Response) GetSendEthereumTransaction() *Response_SendEthereumTransaction {
	if m != nil {
		return m.SendEthereumTransaction
	}
	return nil
}

type Response_DRKeyStoreGet struct {
	MessageKey           []byte   `protobuf:"bytes,1,opt,name=messageKey,proto3" json:"messageKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_DRKeyStoreGet) Reset()         { *m = Response_DRKeyStoreGet{} }
func (m *Response_DRKeyStoreGet) String() string { return proto.CompactTextString(m) }
func (*Response_DRKeyStoreGet) ProtoMessage()    {}
func (*Response_DRKeyStoreGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_e1cf38aee75d74c7, []int{0, 0}
}
func (m *Response_DRKeyStoreGet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_DRKeyStoreGet.Unmarshal(m, b)
}
func (m *Response_DRKeyStoreGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_DRKeyStoreGet.Marshal(b, m, deterministic)
}
func (dst *Response_DRKeyStoreGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_DRKeyStoreGet.Merge(dst, src)
}
func (m *Response_DRKeyStoreGet) XXX_Size() int {
	return xxx_messageInfo_Response_DRKeyStoreGet.Size(m)
}
func (m *Response_DRKeyStoreGet) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_DRKeyStoreGet.DiscardUnknown(m)
}

var xxx_messageInfo_Response_DRKeyStoreGet proto.InternalMessageInfo

func (m *Response_DRKeyStoreGet) GetMessageKey() []byte {
	if m != nil {
		return m.MessageKey
	}
	return nil
}

type Response_DRKeyStoreCount struct {
	Count                uint64   `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_DRKeyStoreCount) Reset()         { *m = Response_DRKeyStoreCount{} }
func (m *Response_DRKeyStoreCount) String() string { return proto.CompactTextString(m) }
func (*Response_DRKeyStoreCount) ProtoMessage()    {}
func (*Response_DRKeyStoreCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_e1cf38aee75d74c7, []int{0, 1}
}
func (m *Response_DRKeyStoreCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_DRKeyStoreCount.Unmarshal(m, b)
}
func (m *Response_DRKeyStoreCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_DRKeyStoreCount.Marshal(b, m, deterministic)
}
func (dst *Response_DRKeyStoreCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_DRKeyStoreCount.Merge(dst, src)
}
func (m *Response_DRKeyStoreCount) XXX_Size() int {
	return xxx_messageInfo_Response_DRKeyStoreCount.Size(m)
}
func (m *Response_DRKeyStoreCount) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_DRKeyStoreCount.DiscardUnknown(m)
}

var xxx_messageInfo_Response_DRKeyStoreCount proto.InternalMessageInfo

func (m *Response_DRKeyStoreCount) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Response_DRKeyStoreAll struct {
	All                  []*Response_DRKeyStoreAll_Key `protobuf:"bytes,1,rep,name=all" json:"all,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Response_DRKeyStoreAll) Reset()         { *m = Response_DRKeyStoreAll{} }
func (m *Response_DRKeyStoreAll) String() string { return proto.CompactTextString(m) }
func (*Response_DRKeyStoreAll) ProtoMessage()    {}
func (*Response_DRKeyStoreAll) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_e1cf38aee75d74c7, []int{0, 2}
}
func (m *Response_DRKeyStoreAll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_DRKeyStoreAll.Unmarshal(m, b)
}
func (m *Response_DRKeyStoreAll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_DRKeyStoreAll.Marshal(b, m, deterministic)
}
func (dst *Response_DRKeyStoreAll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_DRKeyStoreAll.Merge(dst, src)
}
func (m *Response_DRKeyStoreAll) XXX_Size() int {
	return xxx_messageInfo_Response_DRKeyStoreAll.Size(m)
}
func (m *Response_DRKeyStoreAll) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_DRKeyStoreAll.DiscardUnknown(m)
}

var xxx_messageInfo_Response_DRKeyStoreAll proto.InternalMessageInfo

func (m *Response_DRKeyStoreAll) GetAll() []*Response_DRKeyStoreAll_Key {
	if m != nil {
		return m.All
	}
	return nil
}

type Response_DRKeyStoreAll_Key struct {
	Key                  []byte            `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	MessageKeys          map[uint64][]byte `protobuf:"bytes,2,rep,name=messageKeys" json:"messageKeys,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Response_DRKeyStoreAll_Key) Reset()         { *m = Response_DRKeyStoreAll_Key{} }
func (m *Response_DRKeyStoreAll_Key) String() string { return proto.CompactTextString(m) }
func (*Response_DRKeyStoreAll_Key) ProtoMessage()    {}
func (*Response_DRKeyStoreAll_Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_e1cf38aee75d74c7, []int{0, 2, 0}
}
func (m *Response_DRKeyStoreAll_Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_DRKeyStoreAll_Key.Unmarshal(m, b)
}
func (m *Response_DRKeyStoreAll_Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_DRKeyStoreAll_Key.Marshal(b, m, deterministic)
}
func (dst *Response_DRKeyStoreAll_Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_DRKeyStoreAll_Key.Merge(dst, src)
}
func (m *Response_DRKeyStoreAll_Key) XXX_Size() int {
	return xxx_messageInfo_Response_DRKeyStoreAll_Key.Size(m)
}
func (m *Response_DRKeyStoreAll_Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_DRKeyStoreAll_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Response_DRKeyStoreAll_Key proto.InternalMessageInfo

func (m *Response_DRKeyStoreAll_Key) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Response_DRKeyStoreAll_Key) GetMessageKeys() map[uint64][]byte {
	if m != nil {
		return m.MessageKeys
	}
	return nil
}

type Response_SendEthereumTransaction struct {
	Nonce uint32 `protobuf:"varint,1,opt,name=nonce" json:"nonce,omitempty"`
	// must be base 10!
	GasPrice string `protobuf:"bytes,2,opt,name=gasPrice" json:"gasPrice,omitempty"`
	// must be base 10!
	GasLimit string `protobuf:"bytes,3,opt,name=gasLimit" json:"gasLimit,omitempty"`
	To       string `protobuf:"bytes,4,opt,name=to" json:"to,omitempty"`
	// must be base 10!
	Value                string   `protobuf:"bytes,5,opt,name=value" json:"value,omitempty"`
	Data                 string   `protobuf:"bytes,6,opt,name=data" json:"data,omitempty"`
	V                    string   `protobuf:"bytes,7,opt,name=v" json:"v,omitempty"`
	R                    string   `protobuf:"bytes,8,opt,name=r" json:"r,omitempty"`
	S                    string   `protobuf:"bytes,9,opt,name=s" json:"s,omitempty"`
	ChainID              uint32   `protobuf:"varint,10,opt,name=chainID" json:"chainID,omitempty"`
	From                 string   `protobuf:"bytes,11,opt,name=from" json:"from,omitempty"`
	Hash                 string   `protobuf:"bytes,12,opt,name=hash" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_SendEthereumTransaction) Reset()         { *m = Response_SendEthereumTransaction{} }
func (m *Response_SendEthereumTransaction) String() string { return proto.CompactTextString(m) }
func (*Response_SendEthereumTransaction) ProtoMessage()    {}
func (*Response_SendEthereumTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_e1cf38aee75d74c7, []int{0, 3}
}
func (m *Response_SendEthereumTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_SendEthereumTransaction.Unmarshal(m, b)
}
func (m *Response_SendEthereumTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_SendEthereumTransaction.Marshal(b, m, deterministic)
}
func (dst *Response_SendEthereumTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_SendEthereumTransaction.Merge(dst, src)
}
func (m *Response_SendEthereumTransaction) XXX_Size() int {
	return xxx_messageInfo_Response_SendEthereumTransaction.Size(m)
}
func (m *Response_SendEthereumTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_SendEthereumTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_Response_SendEthereumTransaction proto.InternalMessageInfo

func (m *Response_SendEthereumTransaction) GetNonce() uint32 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Response_SendEthereumTransaction) GetGasPrice() string {
	if m != nil {
		return m.GasPrice
	}
	return ""
}

func (m *Response_SendEthereumTransaction) GetGasLimit() string {
	if m != nil {
		return m.GasLimit
	}
	return ""
}

func (m *Response_SendEthereumTransaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Response_SendEthereumTransaction) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Response_SendEthereumTransaction) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Response_SendEthereumTransaction) GetV() string {
	if m != nil {
		return m.V
	}
	return ""
}

func (m *Response_SendEthereumTransaction) GetR() string {
	if m != nil {
		return m.R
	}
	return ""
}

func (m *Response_SendEthereumTransaction) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func (m *Response_SendEthereumTransaction) GetChainID() uint32 {
	if m != nil {
		return m.ChainID
	}
	return 0
}

func (m *Response_SendEthereumTransaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Response_SendEthereumTransaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*Response)(nil), "api_proto.Response")
	proto.RegisterType((*Response_DRKeyStoreGet)(nil), "api_proto.Response.DRKeyStoreGet")
	proto.RegisterType((*Response_DRKeyStoreCount)(nil), "api_proto.Response.DRKeyStoreCount")
	proto.RegisterType((*Response_DRKeyStoreAll)(nil), "api_proto.Response.DRKeyStoreAll")
	proto.RegisterType((*Response_DRKeyStoreAll_Key)(nil), "api_proto.Response.DRKeyStoreAll.Key")
	proto.RegisterMapType((map[uint64][]byte)(nil), "api_proto.Response.DRKeyStoreAll.Key.MessageKeysEntry")
	proto.RegisterType((*Response_SendEthereumTransaction)(nil), "api_proto.Response.SendEthereumTransaction")
}

func init() { proto.RegisterFile("api/pb/response.proto", fileDescriptor_response_e1cf38aee75d74c7) }

var fileDescriptor_response_e1cf38aee75d74c7 = []byte{
	// 460 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0x99, 0xdd, 0xa4, 0xc9, 0xbe, 0x24, 0xb6, 0x0c, 0x95, 0x0e, 0x7b, 0x90, 0xa8, 0x88,
	0x01, 0x61, 0x03, 0x15, 0x54, 0x3c, 0x08, 0xc5, 0x96, 0x22, 0xb1, 0x20, 0x53, 0x0f, 0xde, 0x64,
	0xba, 0x19, 0x9b, 0xc5, 0xcd, 0xcc, 0x32, 0x33, 0x09, 0xec, 0x87, 0xf0, 0xc3, 0x78, 0xf6, 0xab,
	0x79, 0x90, 0x79, 0xd3, 0x26, 0x9b, 0xd0, 0xda, 0xdc, 0xde, 0xff, 0xcd, 0xfb, 0xff, 0xf6, 0xbf,
	0x6f, 0x06, 0x1e, 0x8b, 0xaa, 0x18, 0x57, 0x57, 0x63, 0x23, 0x6d, 0xa5, 0x95, 0x95, 0x59, 0x65,
	0xb4, 0xd3, 0x34, 0x11, 0x55, 0xf1, 0x1d, 0xcb, 0x67, 0x7f, 0x3a, 0xd0, 0xe5, 0x37, 0xa7, 0xf4,
	0x1c, 0x06, 0x53, 0x3e, 0x91, 0xf5, 0xa5, 0xd3, 0x46, 0x9e, 0x4b, 0xc7, 0xe2, 0x21, 0x19, 0xf5,
	0x8e, 0x9f, 0x66, 0xab, 0xf9, 0xec, 0x76, 0x36, 0x3b, 0x6d, 0x0e, 0xf2, 0x4d, 0x1f, 0xbd, 0x80,
	0xfd, 0x75, 0xe3, 0xa3, 0x5e, 0x28, 0xc7, 0x5a, 0x88, 0x7a, 0xfe, 0x7f, 0x14, 0x8e, 0xf2, 0x6d,
	0xef, 0x66, 0xae, 0x93, 0xb2, 0x64, 0xed, 0x5d, 0x72, 0x9d, 0x94, 0x25, 0xdf, 0xf4, 0x51, 0x09,
	0x47, 0x56, 0xaa, 0xe9, 0x99, 0x9b, 0x49, 0x23, 0x17, 0xf3, 0xaf, 0x46, 0x28, 0x2b, 0x72, 0x57,
	0x68, 0xc5, 0xf6, 0x10, 0xf9, 0xea, 0x2e, 0xe4, 0xe5, 0xdd, 0x16, 0x7e, 0x1f, 0x2b, 0x1d, 0xc3,
	0x60, 0x63, 0x3d, 0xf4, 0x09, 0xc0, 0x5c, 0x5a, 0x2b, 0xae, 0xe5, 0x44, 0xd6, 0x8c, 0x0c, 0xc9,
	0xa8, 0xcf, 0x1b, 0x9d, 0xf4, 0x25, 0xec, 0x6f, 0x2d, 0x81, 0x1e, 0x42, 0x3b, 0xc7, 0xc5, 0xf9,
	0xe9, 0x16, 0x0f, 0x22, 0xfd, 0x4b, 0x9a, 0x68, 0xff, 0x4b, 0x6f, 0x21, 0x16, 0x65, 0xc9, 0xc8,
	0x30, 0x1e, 0xf5, 0x8e, 0x5f, 0x3c, 0xb8, 0x91, 0x6c, 0x22, 0x6b, 0xee, 0x1d, 0xe9, 0x6f, 0x02,
	0xf1, 0x44, 0xd6, 0xf4, 0x00, 0xe2, 0x9f, 0xab, 0x50, 0xbe, 0xa4, 0xdf, 0xa0, 0xb7, 0xce, 0x66,
	0x59, 0x84, 0xe8, 0x37, 0x3b, 0xa1, 0xb3, 0x8b, 0xb5, 0xf1, 0x4c, 0x39, 0x53, 0xf3, 0x26, 0x2a,
	0xfd, 0x00, 0x07, 0xdb, 0x03, 0xcd, 0xef, 0xb7, 0xc2, 0xf7, 0x0f, 0xa1, 0xbd, 0x14, 0xe5, 0x42,
	0xb2, 0x08, 0x33, 0x05, 0xf1, 0x3e, 0x7a, 0x47, 0xd2, 0x5f, 0x11, 0x1c, 0xdd, 0x73, 0x1b, 0xde,
	0xa5, 0xb4, 0xca, 0x25, 0x92, 0x06, 0x3c, 0x08, 0x9a, 0x42, 0xf7, 0x5a, 0xd8, 0x2f, 0xa6, 0xc8,
	0x03, 0x2e, 0xe1, 0x2b, 0x7d, 0x73, 0xf6, 0xb9, 0x98, 0x17, 0xe1, 0xa5, 0x87, 0x33, 0xd4, 0xf4,
	0x11, 0x44, 0x4e, 0xe3, 0xa3, 0x4d, 0x78, 0xe4, 0xf4, 0x3a, 0x53, 0x1b, 0x5b, 0x41, 0x50, 0x0a,
	0xad, 0xa9, 0x70, 0x02, 0x1f, 0x4f, 0xc2, 0xb1, 0xa6, 0x7d, 0x20, 0x4b, 0xd6, 0xc1, 0x06, 0x59,
	0x7a, 0x65, 0x58, 0x37, 0x28, 0xe3, 0x95, 0x65, 0x49, 0x50, 0x96, 0x32, 0xe8, 0xe4, 0x33, 0x51,
	0xa8, 0x4f, 0xa7, 0x0c, 0x30, 0xf3, 0xad, 0xf4, 0xdc, 0x1f, 0x46, 0xcf, 0x59, 0x2f, 0x70, 0x7d,
	0xed, 0x7b, 0x33, 0x61, 0x67, 0xac, 0x1f, 0x7a, 0xbe, 0xbe, 0xda, 0xc3, 0xfb, 0x78, 0xfd, 0x2f,
	0x00, 0x00, 0xff, 0xff, 0x40, 0x68, 0xbc, 0x0b, 0xe8, 0x03, 0x00, 0x00,
}
