// Code generated by protoc-gen-go. DO NOT EDIT.
// source: response.proto

package api_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Response struct {
	SendEthereumTransaction *Response_SendEthereumTransaction `protobuf:"bytes,6,opt,name=sendEthereumTransaction,proto3" json:"sendEthereumTransaction,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                          `json:"-"`
	XXX_unrecognized        []byte                            `json:"-"`
	XXX_sizecache           int32                             `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_91129bf3a636fcb7, []int{0}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSendEthereumTransaction() *Response_SendEthereumTransaction {
	if m != nil {
		return m.SendEthereumTransaction
	}
	return nil
}

type Response_SendEthereumTransaction struct {
	Nonce uint32 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// must be base 10!
	GasPrice string `protobuf:"bytes,2,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	// must be base 10!
	GasLimit string `protobuf:"bytes,3,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	To       string `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	// must be base 10!
	Value                string   `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Data                 string   `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	V                    uint32   `protobuf:"varint,7,opt,name=v,proto3" json:"v,omitempty"`
	R                    string   `protobuf:"bytes,8,opt,name=r,proto3" json:"r,omitempty"`
	S                    string   `protobuf:"bytes,9,opt,name=s,proto3" json:"s,omitempty"`
	ChainID              uint32   `protobuf:"varint,10,opt,name=chainID,proto3" json:"chainID,omitempty"`
	From                 string   `protobuf:"bytes,11,opt,name=from,proto3" json:"from,omitempty"`
	Hash                 string   `protobuf:"bytes,12,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_SendEthereumTransaction) Reset()         { *m = Response_SendEthereumTransaction{} }
func (m *Response_SendEthereumTransaction) String() string { return proto.CompactTextString(m) }
func (*Response_SendEthereumTransaction) ProtoMessage()    {}
func (*Response_SendEthereumTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_91129bf3a636fcb7, []int{0, 0}
}
func (m *Response_SendEthereumTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_SendEthereumTransaction.Unmarshal(m, b)
}
func (m *Response_SendEthereumTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_SendEthereumTransaction.Marshal(b, m, deterministic)
}
func (dst *Response_SendEthereumTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_SendEthereumTransaction.Merge(dst, src)
}
func (m *Response_SendEthereumTransaction) XXX_Size() int {
	return xxx_messageInfo_Response_SendEthereumTransaction.Size(m)
}
func (m *Response_SendEthereumTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_SendEthereumTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_Response_SendEthereumTransaction proto.InternalMessageInfo

func (m *Response_SendEthereumTransaction) GetNonce() uint32 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Response_SendEthereumTransaction) GetGasPrice() string {
	if m != nil {
		return m.GasPrice
	}
	return ""
}

func (m *Response_SendEthereumTransaction) GetGasLimit() string {
	if m != nil {
		return m.GasLimit
	}
	return ""
}

func (m *Response_SendEthereumTransaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Response_SendEthereumTransaction) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Response_SendEthereumTransaction) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Response_SendEthereumTransaction) GetV() uint32 {
	if m != nil {
		return m.V
	}
	return 0
}

func (m *Response_SendEthereumTransaction) GetR() string {
	if m != nil {
		return m.R
	}
	return ""
}

func (m *Response_SendEthereumTransaction) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func (m *Response_SendEthereumTransaction) GetChainID() uint32 {
	if m != nil {
		return m.ChainID
	}
	return 0
}

func (m *Response_SendEthereumTransaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Response_SendEthereumTransaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*Response)(nil), "api_proto.Response")
	proto.RegisterType((*Response_SendEthereumTransaction)(nil), "api_proto.Response.SendEthereumTransaction")
}

func init() { proto.RegisterFile("response.proto", fileDescriptor_response_91129bf3a636fcb7) }

var fileDescriptor_response_91129bf3a636fcb7 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x14, 0xc4, 0xe5, 0xf4, 0x5f, 0xf2, 0x5a, 0x3a, 0x58, 0x48, 0x7d, 0xea, 0x14, 0x31, 0x45, 0x42,
	0xca, 0x00, 0x5f, 0x01, 0x06, 0x24, 0x06, 0x14, 0xd8, 0x91, 0x49, 0x1f, 0xc4, 0x12, 0xb1, 0x23,
	0xdb, 0xcd, 0xce, 0x07, 0xe0, 0x3b, 0x23, 0x3f, 0xb7, 0x99, 0xe8, 0x76, 0xbf, 0x3b, 0xdf, 0xc9,
	0x36, 0x6c, 0x1d, 0xf9, 0xc1, 0x1a, 0x4f, 0xf5, 0xe0, 0x6c, 0xb0, 0xb2, 0x50, 0x83, 0x7e, 0x67,
	0x79, 0xf3, 0x33, 0x83, 0xbc, 0x39, 0xa5, 0x92, 0x60, 0xe7, 0xc9, 0x1c, 0x1e, 0x43, 0x47, 0x8e,
	0x8e, 0xfd, 0x9b, 0x53, 0xc6, 0xab, 0x36, 0x68, 0x6b, 0x70, 0x59, 0x8a, 0x6a, 0x7d, 0x77, 0x5b,
	0x4f, 0xcd, 0xfa, 0xdc, 0xaa, 0x5f, 0xff, 0xaf, 0x34, 0x97, 0xb6, 0xf6, 0xbf, 0x19, 0xec, 0x2e,
	0x94, 0xe4, 0x35, 0x2c, 0x8c, 0x35, 0x2d, 0xa1, 0x28, 0x45, 0x75, 0xd5, 0x24, 0x90, 0x7b, 0xc8,
	0xbf, 0x94, 0x7f, 0x71, 0xba, 0x25, 0xcc, 0x4a, 0x51, 0x15, 0xcd, 0xc4, 0xa7, 0xec, 0x59, 0xf7,
	0x3a, 0xe0, 0x6c, 0xca, 0x98, 0xe5, 0x16, 0xb2, 0x60, 0x71, 0xce, 0x6e, 0x16, 0x6c, 0x5c, 0x1f,
	0xd5, 0xf7, 0x91, 0x70, 0xc1, 0x56, 0x02, 0x29, 0x61, 0x7e, 0x50, 0x41, 0xf1, 0x1b, 0x8b, 0x86,
	0xb5, 0xdc, 0x80, 0x18, 0x71, 0xc5, 0x77, 0x10, 0x63, 0x24, 0x87, 0x39, 0xc7, 0xc2, 0x45, 0xf2,
	0x58, 0x24, 0xf2, 0x12, 0x61, 0xd5, 0x76, 0x4a, 0x9b, 0xa7, 0x07, 0x04, 0x3e, 0x7f, 0xc6, 0xb8,
	0xfb, 0xe9, 0x6c, 0x8f, 0xeb, 0xb4, 0x1b, 0x75, 0xf4, 0x3a, 0xe5, 0x3b, 0xdc, 0x24, 0x2f, 0xea,
	0x8f, 0x25, 0x7f, 0xe8, 0xfd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x62, 0x5f, 0xb3, 0xbd, 0xa7,
	0x01, 0x00, 0x00,
}
